const data = {
    products: [
        {
            _id: '1',
            name: 'Moyu Meilong 3M',
            slug: 'moyu-3x3',
            category: '3x3',
            images: '/images/p1.jpg',
            price: 25,
            countInStock: 20,
            brand: 'Moyu',
            rating: 4.5,
            numReviews: 10,
            description: "Magnetic speed rubik's cube 3x3",
        },
        {
            _id: '2',
            name: 'Moyu Meilong 4M',
            slug: 'moyu-4x4',
            category: '4x4',
            images: '/images/p2.jpg',
            price: 25,
            countInStock: 15,
            brand: 'Moyu',
            rating: 4.5,
            numReviews: 10,
            description: "Magnetic speed rubik's cube 4x4",
        },
        {
            _id: '3',
            name: 'Moyu Meilong 5M',
            slug: 'moyu-5x5',
            category: '5x5',
            images: '/images/p3.jpg',
            price: 25,
            countInStock: 25,
            brand: 'Moyu',
            rating: 4.5,
            numReviews: 10,
            description: "Magnetic speed rubik's cube 5x5",
        },
        {
            _id: '4',
            name: 'Moyu Meilong 6M',
            slug: 'moyu-6x6',
            category: '6x6',
            images: '/images/p4.jpg',
            price: 50,
            countInStock: 25,
            brand: 'Moyu',
            rating: 4,
            numReviews: 25,
            description: "Magnetic speed rubik's cube 6x6",
        },
    ],
};

module.exports = data;
